auth:
  mfa: true
  password_min_length: 10
  max_failed_attempts: 5
session:
  auto_lock_minutes: 15
logging:
  enabled: true
  retention_days: 90   # partial
remote_access:
  vpn_required: true
network:
  tls_enabled: true
storage:
  encrypt_at_rest: true
iam:
  enforce_least_privilege: true
# wireless.enterprise_auth omitted -> policy-only
# scanner.enabled omitted -> policy-only
# time.ntp_sync omitted -> policy-only
  enabled: true
incident:
  plan_documented: true
training:
  security_awareness: true
